### ISSUE TITLE
[BUG] Tutorial error

### ISSUE THREAD

**Issue by jpober** [21cmfast/21CMMC#20]
**Describe the bug:**

Minor bug in mcmc_intro tutorial.  

`from py21cmmc.mcmc import analyse` should be `from py21cmmc import analyse` (I think)

**To Reproduce:**
Run the first import cell.

**Comment by steven-murray** [comment]
Thanks @jpober. I am working on a branch fixing a few of these documentation issues, that arose in the re-packaging of 21cmFAST and 21CMMC.

**Comment by binnietom** [comment]
Hello, 
There are similar type-o's in the mcmc_global.ipynb ( they mainly retain the syntax of the previous Hybrid21CM) -  so any core must be 'py21cmmc.core.<>' and likelihoods 'py21cmmc.likelihood.<>' (rather than 'py21cmmc.mcmc.<>'). 

Also with the Luminosity function part at the bottom: it is redshift not redshifts and there needs to be a sigma argument. 
- Speaking of this I wanted to ask what values of sigma would be a sensible choice for generating luminosity function likelihoods?
Thanks,
Tom

**Comment by steven-murray** [comment]
@binnietom noted. 

I am not sure what a sensible choice for the noise in the luminosity function. Perhaps @BradGreig knows?

**Comment by BradGreig** [comment]
For the luminosity functions, you should be passing the observational error bars from the specific observation that you are using as a prior rather than a fixed, constant sigma.

You can find the actual values used in the older 21CMMC located here https://github.com/BradGreig/21CMMC/tree/master/21CMMC_SourceCode/Programs/MockObs/GalaxyParams/LFs
