### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by parphyam** [21cmfast/21CMMC#55]
**Describe what you would like to do**

Do a parameter estimation for a 21cmFAST lightcone cube without making the lightcone again.
**What I've tried**

Hi, 
If I already have a power spectrum .npz file which is constructed from 21cmFAST and I want to do a parameter estimation from the same, how can that be done? It appears from the documentation ([https://21cmmc.readthedocs.io/en/latest/tutorials/mcmc_lightcone.html]), that one needs to put in all the parameters (HII_DIM, BOX_LEN and so on) to proceed and thus there seems to be no use of the actual power spectrum constructed previously in 21cmFAST. Also, if this does not work, how is the visibility simulated with some software (say CASA) be used ?

**Comment by steven-murray** [comment]
Hi @parphyam, this should definitely be possible. 

You can setup your likelihood with the `datafile=` parameter, passing in the `.npz` file. You still need to pass in the parameters (`HII_DIM`, `BOX_LEN`,...) because your models may have a different resolution than your (mock) data. Hopefully this makes sense.

When you talk about visibilities, what are you using them for? By default, 21cmMC does not deal with actual visibilities at all -- it just does FTs of the lightcones. There is a plugin: https://github.com/BellaNasirudin/py21cmmc_fg that kind of adds this functionality, but you'll have to do some work on it if you want to use CASA.

**Comment by parphyam** [comment]
Hi, 
Thank you for the answer. So essentially if I manage to extract a power spectrum from some mock visibility, then I should be able to perform parameter estimation on that using 21CMMC, right?

**Comment by steven-murray** [comment]
Yes!

**Comment by steven-murray** [comment]
@parphyam I am closing this as resolved, but feel free to reopen as necessary.
