### ISSUE TITLE
[BUG] Odd behaviour for zero likelihood

### ISSUE THREAD

**Issue by NGillet** [21cmfast/21CMMC#9]
Hi, 

I am testing the MCMC "only" features i.e. as much as possible independently of 21cmFast.

I build a simple core and likelihood :

    class MyDummyCore(mcmc.CoreBase):
        def __init__(self, dummy,
                 *args, **kwargs ):
            super().__init__(*args, **kwargs)
            self.dummy = dummy
        
        def build_model_data(self, ctx):
            super().build_model_data(ctx)
            ctx.add("dummy", self.dummy)
        
    class MyDummyLikelihood(mcmc.LikelihoodBase):    
        def reduce_data(self, ctx): 
            params = ctx.getParams()
            return dict(M_TURN=params[0], ALPHA_STAR=params[1])
    
        def computeLikelihood(self, model):
            ### ok
            #return -0.5* ( (model['M_TURN']-9)**2/0.25**2 + (model['ALPHA_STAR'])**2/0.125**2 )
        
            ### border effect ?
            #return -0.5* ( (model['M_TURN']-9)**2/1.**2 + (model['ALPHA_STAR'])**2/0.5**2 )
        
            ### cross ?
            return 0.
   
    core = MyDummyCore( 0. )
    likelihood = MyDummyLikelihood(  )

and a simple MCMC: 

    chain = mcmc.run_mcmc(
    core, likelihood,        # Use lists if multiple cores/likelihoods required. These will be eval'd in order.
    datadir='data_dummy',    # Directory for all outputs
    model_name=model_name,   # Filename of main chain output
    params=dict(             # Parameter dict as described above.
        M_TURN = [9.0, 6.0, 12.0, 4.0], # fid, rangeMin, rangeMax
        ALPHA_STAR = [0.0, -1.5, 1.5, 2.0],
    ), 
    walkersRatio=4,          # The number of walkers will be walkersRatio*nparams
    burninIterations=0,      # Number of iterations to save as burnin. Recommended to leave as zero.
    sampleIterations=10000,    # Number of iterations to sample, per walker.
    threadCount=16,           # Number of processes to use in MCMC (best as a factor of walkersRatio)
    continue_sampling=False  # Whether to contine sampling from previous run *up to* sampleIterations.
)

So the lnL is set to constant 0. I expect a flat distibution of the paramters in the end :
but there is a clear X shape... I do not think this is a border issue. I suspect a deeper problem in the mcmc...

![MCMC_cross](https://user-images.githubusercontent.com/12394419/63951147-8570dd80-ca7d-11e9-9510-98ac5fd403c0.png)

then, in the likelihood function, if the distributions are wide gaussian, the result is boxy instead of perfectly round as expected:

![MCMC_box](https://user-images.githubusercontent.com/12394419/64008146-cf0d0700-cb15-11e9-99ce-f1676ceaa3f9.png)

**Comment by NGillet** [comment]
The defaults flag_options struct has USE_MASS_DEPENDENT_ZETA set to False. This should be set to True if you are using F_STAR and F_ESC.

It solves the problem and produces different light-cone global xHI (for neutral fraction and tau_e MCMC).

**Comment by steven-murray** [comment]
I suspect these may be due to priors on the parameters (i.e. their bounds). Can you try changing their bounds and see if the resulting posteriors are affected?

The cross is very strange though. I'll have to look into it a bit more.

**Comment by NGillet** [comment]
The cross is independent of the bound. I changed them to :
    M_TURN = [9.0, 5.0, 13.0, 5.0]
    ALPHA_STAR = [0.0, -2.5, 2.5, 3.0]
and it change nothing.
I think the boxy shape is related to the same "problem". 

Is there a way to control the initial position of the walkers ?

**Comment by steven-murray** [comment]
So sorry for the late reply!

OK so this definitely does seem like a problem. 

You _can_ control the initial position of the walkers, but I'm afraid it's not simple.

First, you'll need to define a new Generator class like so:

```
class MyPositionGenerator:
    def setup(self, sampler):
        self.sampler = sampler

    def generate(self):
        # return an array with shape (nwalkers, nparams) of your initial parameters
        # the default implementation is this:
        return [self.sampler.paramValues+np.random.normal(size=self.sampler.paramCount)*self.sampler.paramWidths for i in range(self.sampler.nwalkers)]
```

then you need to pass this to the `run_mcmc` function:

```
run_mcmc(..., initPositionGenerator=MyPositionGenerator())
```

**Comment by NGillet** [comment]
I tried to change the initial walker position generator but **it changes nothing** to the final "crossed" distribution. 
I also tried it in a higher dimension and it gives the same result.

There is another generator in Cosmohammer to do a flat initial distribution:
in CosmoHammerSampler.py

    from cosmoHammer.util import FlatPositionGenerator

    class CosmoHammerSampler(CHS):
        def __init__(blablabla):
            ...
        super().__init__(
            ...
            ########
            initPositionGenerator=FlatPositionGenerator(),
            ########
            ... )

**Comment by NGillet** [comment]
Have you been able to reproduce the "crossed" distribution?
It would be nice to try, it does not take a long time. Just copy/paste the core and likelihood.

There are 2 scenarios : (i) I made mistake (70%  I would say) or (ii) there is a problem

(i) my core, likelihood, and run_mcmc are relatively simple, I do not see an obvious mistake. 

(ii) the "crossed" distribution seems to suggest the walkers are not independent... I looked at the affine invariant sampler in `ensemble.py` and I did not find any obvious problem. The chain in the ensemble.py sample is the same as the one recover at the end in the chain object. 

I found a difference in the acceptance array:
1) the acceptance array seems to be always at 1 for all walkers at the first iteration. While it is not the case.
2) in the case of the constant likelihood (`def computeLikelihood(self, model): return 0.`), the stored acceptance in the chain object is full of 0 (except the first iteration full of 1). But it is wrong because I printed the acceptance directly in the sampling function, and it is not always 0.
<img width="841" alt="Capture d’écran 2019-09-24 à 15 04 53" src="https://user-images.githubusercontent.com/12394419/65517836-9c231c80-dee3-11e9-8e52-5fc1371d23fe.png">

**Comment by steven-murray** [comment]
Thanks @NGillet, this is super helpful. I will try to run these examples myself sometime this week, though I _might_ not get to it til next week as I have a lot on. 

Will you be in Pisa next week? Perhaps we can hit it hard then.

**Comment by steven-murray** [comment]
Thinking about this a bit further:

For your "zero" likelihood, the posterior should be equal to the prior. If your prior is flat, `emcee` can have problems with it, because of its edge conditions. I don't know if it will give you a cross, but I guess that kind of makes sense.

For a Gaussian that is wider than the flat prior, you'd expect to see something a little box-like. I don't quite understand the cross though, because you'd expect the corners to have the _lowest_ sampling. 

The acceptance being zero everywhere doesn't make sense, because it should be pretty much exactly half in this case. We'll have to look into that too.

**Comment by binnietom** [comment]
I've noticed the walkers begin their run close to the fiducial points - looking deeper into the code (and the CosmoHammer's git page) taking the intipositionGenerator with no arguments defaults to the 'SampleBallPositionGenerator'. This puts Gaussians with mean=the fiducial point and variance of the 4th input parameter argument as the prior. 
i.e. it doesn't use the min or max inputted:
[self.sampler.params[:,0]+np.random.normal(size=self.sampler.paramCount)*self.sampler.params[:,3] for i in range(self.sampler.nwalkers)]   .

Other than rewriting the class structure as above, an easier way to distribute the walkers evenly across the priors is to replace line '283' in CosmoHammerSampler.py with
tmp_pos = [self.params[:,1] + np.random.random(len([self.params]))*(self.params[:,2]-self.params[:,1]) for j in range(self.nwalkers)]   .

Ideally, the user should toggle between using Gaussian or flat priors.

I suspect If you run with two parameters where their correlation depends on the value of one of them, e.g. alpha and M_turn, then starting around the fiducial would only lead the walkers to trail outwards along with either the correlation or anticorrelation (if alpha is positive or negative) - giving the x shape? (Since Emcee updates its walkers in pairs this could get exaggerated).

 I hope this helps!
Tom

**Comment by steven-murray** [comment]
I'm pretty sure this problem is due to our forcing the proposals to be within the bounds here: https://github.com/21cmfast/21CMMC/blob/df8d177ba9dfcbbe0a8985d04343d96a8daf54c6/src/py21cmmc/ensemble.py#L66

For a similar test likelihood that @NGillet has above, I get a similar output density:

![image](https://user-images.githubusercontent.com/1272030/82617548-40e61e80-9b85-11ea-981d-08df1c37d1bb.png)

Commenting out this "feature", I get

![image](https://user-images.githubusercontent.com/1272030/82617566-4ba0b380-9b85-11ea-9779-73865c3ca110.png)

This is only for 5000 samples, hence the wobbliness, but you can see that it is definitely a different posterior, and getting flatter.

I invite @BradGreig and @andreimesinger for comment on this, as @BradGreig suggested doing something like this -- potentially he knows a way to do this (and get the better load balancing) while not having the bad side effect.

**Comment by BradGreig** [comment]
@steven-murray, yeah, I agree that this is likely to be the case. Was this test performed using Gaussian Ball Initial conditions or random uniform initial conditions? (as Tom noted above) If you are re-proposing new positions after they exceed their bounds with a Gaussian Ball then you'd expect these re-sampled positions to congregate around the centroid of the Gaussian (central limit theorem). If you start with Random Uniform initial conditions, you'd wouldn't expect any preferred direction on re-sampled parameters.

**Comment by steven-murray** [comment]
The initial conditions are a Gaussian ball. But the proposal does not use the initial conditions, it uses whatever internal stretch move covariance the ensemble has generated.

**Comment by BradGreig** [comment]
But the proposed stretch is based on the original position of the walker. It splits the walker sample up into two, then proposes a new position based on the previous. If the original position is in a Gaussian ball, then its only going to look for new positions around the Gaussian ball. If it starts within Random Initial conditions, it'll move from these random positions.

**Comment by steven-murray** [comment]
But this shouldn't affect the final distribution, right? The idea is that a small ball will quickly spread to fill the posterior, and lose memory of the initial conditions. It's possible that by losing detailed balance as we have, by implementing the forcing of only "good" proposals, this is contravened, so that the initial conditions do indeed play a role, but I'm not convinced (I can quickly convince myself though...).

**Comment by andreimesinger** [comment]
yes, without detailed balance, the equilibrium walker distribution doesn’t reflect the posterior

**Comment by steven-murray** [comment]
OK saw @BradGreig's comments in Slack showing that this is *not* an initial conditions thing, and it is entirely due to this load-balancing "feature". Opened a PR to remove it.
